// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	user "ads/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryDbUser is an autogenerated mock type for the RepositoryDbUser type
type RepositoryDbUser struct {
	mock.Mock
}

// CheckUserDb provides a mock function with given fields: id
func (_m *RepositoryDbUser) CheckUserDb(id int) (*user.UserDb, error) {
	ret := _m.Called(id)

	var r0 *user.UserDb
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*user.UserDb, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *user.UserDb); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserDb)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUserDb provides a mock function with given fields: _a0
func (_m *RepositoryDbUser) CreateUserDb(_a0 user.UserDb) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(user.UserDb) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(user.UserDb) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(user.UserDb) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserDb provides a mock function with given fields: id
func (_m *RepositoryDbUser) DeleteUserDb(id int) (*user.UserDb, error) {
	ret := _m.Called(id)

	var r0 *user.UserDb
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*user.UserDb, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *user.UserDb); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserDb)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: username, password
func (_m *RepositoryDbUser) GetUser(username string, password string) (*user.UserDb, error) {
	ret := _m.Called(username, password)

	var r0 *user.UserDb
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*user.UserDb, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *user.UserDb); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserDb)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserDb provides a mock function with given fields: username, id
func (_m *RepositoryDbUser) UpdateUserDb(username string, id int) (*user.UserDb, error) {
	ret := _m.Called(username, id)

	var r0 *user.UserDb
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*user.UserDb, error)); ok {
		return rf(username, id)
	}
	if rf, ok := ret.Get(0).(func(string, int) *user.UserDb); ok {
		r0 = rf(username, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserDb)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(username, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepositoryDbUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryDbUser creates a new instance of RepositoryDbUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryDbUser(t mockConstructorTestingTNewRepositoryDbUser) *RepositoryDbUser {
	mock := &RepositoryDbUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
