version: '3.8'

services:
  ads:
    restart: always
    build: ./
    command: go run cmd/main/main.go
    ports:
      - 18080:18080
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    restart: always
    image: postgres:alpine
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - 5432:5432
