version: '3.8'

services:
  ads:
    restart: always
    build: ./
    command: ./opt/ads/app
    ports:
      - 18080:18080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
